#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 11 22:58:48 2016

@author: Will Cox 
"""

from pygame.locals import *
import pygame
import time

class game_player():
    
    x = []
    y = []
    step = 44
    direction = 0
    length = 3
    
    updateCountMax = 2
    updateCount = 0
    
    def __init__(self,length):
        self.length = length
        for i in range(0,length):
            self.x.append(0)
            self.y.append(0)
        
        
    def update(self):
        
        self.updateCount =  self.updateCount = 1
        if self.updateCount > self.updateCountMax:
            
            #update previous positions
            for i in range(self.length-1,0,-1):
                print ("self.x[" + str(i) + "] = self.x[" + str(i-1) + "]")
                self.x[i] = self.x[i-1]
                self.y[i] = self.y[i-1]
                
            if self.direction == 0:
                self.x[0] = self.x[0] + self.step
            if self.direction == 1:
                self.x[0] = self.x[0] - self.step
            if self.direction == 2:
                self.y[0] = self.y[0] - self.step
            if self.direction == 3:
                self.y[0] = self.y[0] + self.step
            
            self.updaetCount = 0
    
    def move_left(self):
        self.direction = 1
        
    def move_right(self):
        self.direction = 0
        
    def move_up(self):
        self.direction = 2
        
    def move_down(self):
        self.direction = 3
        
    def draw(self, surface,image):
        for i in range(0,self.length):
            surface.blit(image,(self.x[i],self.y[i]))
        
class App():
    windowWidth = 800
    windowHeigth = 600
    player = 0
    
    def __init__(self):
        self.running = True
        self.display_surf = None
        self.image_surf = None
        self.player = game_player(10)
        
    def on_init(self):
        pygame.init()
        self._display_surf = pygame.display.set_mode((self.windowWidth,self.windowHeigth),pygame.HWSURFACE)
        
        self.running = True
        self.image_surf = pygame.image.load("car_img.png").convert()
    
    def on_event(self,event):
        if event.type == QUIT:
            self._running = False
            
    def on_loop(self):
        pass
    
    def on_render(self):
        self._display_surf.fill((0,0,0))
        self.player.draw(self._display_surf, self.image_surf)
        pygame.display.flip()
    
    def on_cleanup(self):
        pygame.quit()
        
    def on_execute(self):
        if self.on_init() == False:
            self.running = False
        while(self.running):
            pygame.event.pump()
            keys = pygame.key.get_pressed()
            
            if (keys[K_RIGHT]):
                self.player.move_right()
                
            if (keys[K_LEFT]):
                self.player.move_left()
                
            if (keys[K_UP]):
                self.player.move_up()
                
            if (keys[K_DOWN]):
                self.player.move_down
            
            if (keys[K_ESCAPE]):
                self.running = False
                
            self.on_loop()
            self.on_render()
            
            time.sleep (50.0 /100.0);
        self.on_cleanup()
        
if __name__ == "__main__" :
    theApp = App()
    theApp.on_execute()
        
        